my_blog/course/urls.py
from course import views
from django.urls import path

app_name = "course"
urlpatterns = [
    path("courses", views.courses, name="course-list"),
]

my_blog/family/urls.py
from django.urls import path
from family import views

app_name = "family"
urlpatterns = [
    path("family_list", views.family_list, name="family-list"),
]

my_blog/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("home", views.index, name="index"),
]

my_blog/my_blog/urls.py
from course.views import create_course
from django.contrib import admin
from django.urls import include, path
from family.views import create_family
from profesor.views import create_profesor
from student.views import create_student

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("create_course/<str:name>/<int:code>", create_course),
    path(
        "create_profesor/<str:name>/<str:last_name>/<str:email>/<str:profession>",
        create_profesor,
    ),
    path("create_student/<str:name>/<str:last_name>/<str:email>", create_student),
    path("course/", include("course.urls")),
    path("student/", include("student.urls")),
    path("create_family/<str:name>/<str:last_name>/<str:email>/<str:birth_date>", create_family),
    path("family/", include("family.urls")),
]

my_blog/student/urls.py
from django.urls import path
from student import views

app_name = "student"
urlpatterns = [
    path("students", views.students, name="student-list"),
]

my_blog/course/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=40)
    code = models.IntegerField()

    def __str__(self):
        return f"Course: {self.name} | code: {self.code}"


class Homework(models.Model):
    name = models.CharField(max_length=40)
    due_date = models.DateField()
    is_delivered = models.BooleanField()

my_blog/family/models.py
from django.db import models


class Family(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    birth_date = models.DateField()

my_blog/home/models.py
from django.db import models

# Create your models here.

my_blog/profesor/models.py
from django.db import models


class Profesor(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    profession = models.CharField(max_length=40)

my_blog/student/models.py
from django.db import models

class Student(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()

my_blog/course/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from course.models import Course


def create_course(request, name: str, code: int):

    template = loader.get_template("template_course.html")

    course = Course(name=name, code=code)
    course.save()  # save into the DB

    context_dict = {"course": course}
    render = template.render(context_dict)
    return HttpResponse(render)


def courses(request):
    courses = Course.objects.all()

    context_dict = {"courses": courses}

    return render(
        request=request,
        context=context_dict,
        template_name="course/course_list.html",
    )

my_blog/family/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from family.models import Family


def create_family(request, name: str, last_name: str, email: str, birth_date: int):

    template = loader.get_template("template_family.html")
    birth_date = datetime.strptime(birth_date, '%Y-%m-%d')
    family = Family(name=name, last_name=last_name, email=email, birth_date=birth_date)
    family.save()  # save into the DB

    context_dict = {"family": family}
    render = template.render(context_dict)
    return HttpResponse(render)





def family_list(request):
    family_list = Family.objects.all()

    context_dict = {"family_list": family_list}

    return render(
        request=request,
        context=context_dict,
        template_name="family/family_list.html",
    )

my_blog/home/views.py
from django.shortcuts import render

def index(request):
    return render(
        request=request,
        context={},
        template_name="home/index.html",
    )

my_blog/profesor/views.py
from django.http import HttpResponse
from django.template import loader

from profesor.models import Profesor


def create_profesor(request, name: str, last_name: str, email: str, profession: str):

    template = loader.get_template("template_profesor.html")

    profesor = Profesor(
        name=name, last_name=last_name, email=email, profession=profession
    )
    profesor.save()  # save into the DB

    context_dict = {"profesor": profesor}
    render = template.render(context_dict)
    return HttpResponse(render)

my_blog/student/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from student.models import Student


def create_student(request, name: str, last_name: str, email: str):

    template = loader.get_template("template_student.html")

    student = Student(name=name, last_name=last_name, email=email)
    student.save()  # save into the DB

    context_dict = {"student": student}
    render = template.render(context_dict)
    return HttpResponse(render)





def students(request):
    students = Student.objects.all()

    context_dict = {"students": students}

    return render(
        request=request,
        context=context_dict,
        template_name="student/student_list.html",
    )

my_blog/course/templates/course/course_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos</title>
</head>
<body>

    <h2>Lista de Cursos</h2>

    <hr></hr>
    <ul>
        {% for course in courses %}
        <li>
            {{course}}
        </li>
        {% endfor %}
    </ul>

</body>
</html>

my_blog/family/templates/family/family_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estudiantes</title>
</head>
<body>

    <h2>Lista de familiares</h2>

    <hr></hr>
    
    {% for family in family_list %}
    <ul>
        Familiar {{family.id}}
        <li>
            Nombre: {{family.name}} {{family.last_name}}
        </li>
        <li>
            Email: {{family.email}}
        </li>
        <li>
            Fecha de nacimiento: {{family.birth_date}}
        </li>
    </ul>
    {% endfor %}
    

</body>
</html>

my_blog/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Home</title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'course:course-list' %}">Cursos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'student:student-list' %}">Estudiantes</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#!">Profesores</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/home/assets/img/home-bg.jpg">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>

my_blog/student/templates/student/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estudiantes</title>
</head>
<body>

    <h2>Lista de Estudiantes</h2>

    <hr></hr>
    <ul>
        {% for student in students %}
        <li>
            {{student}}
        </li>
        {% endfor %}
    </ul>

</body>
</html>

my_blog/templates/template_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course</title>
</head>
<body>
    <h1>The course created is: {{course.name}}</h1>
    <h3>Code: {{course.code}}</h3>
</body>
</html>

my_blog/templates/template_family.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Family</title>
</head>
<body>
    <h1>The family created is: {{ family.name }} {{ family.last_name }}</h1>
    <h3>Email: {{ family.email }}</h3>
    <h3>Date of birth: {{ family.birth_date }}</h3>
</body>
</html>

my_blog/templates/template_profesor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profesor</title>
</head>
<body>
    <h1>The profesor created is: {{ profesor.name }} {{ profesor.last_name }}</h1>
    <h3>Email: {{ profesor.email }}</h3>
    <h3>Profession: {{ profesor.profession }}</h3>
</body>
</html>

my_blog/templates/template_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student</title>
</head>
<body>
    <h1>The student created is: {{ student.name }} {{ student.last_name }}</h1>
    <h3>Email: {{ student.email }}</h3>
</body>
</html>